name = "NonLinearReactionAdvectionDiffusionWithFrontData"
uuid = "db403dc9-80bf-46d2-a311-18f56bc0e108"
authors = ["Andrey Borzunov"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
